// Code generated by protoc-gen-go. DO NOT EDIT.
// source: spec.proto

package protbuf_adapter

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Schedule struct {
	ID                   int32    `protobuf:"varint,1,opt,name=ID,proto3" json:"ID,omitempty"`
	EventsList           []*Event `protobuf:"bytes,2,rep,name=EventsList,proto3" json:"EventsList,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Schedule) Reset()         { *m = Schedule{} }
func (m *Schedule) String() string { return proto.CompactTextString(m) }
func (*Schedule) ProtoMessage()    {}
func (*Schedule) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{0}
}

func (m *Schedule) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Schedule.Unmarshal(m, b)
}
func (m *Schedule) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Schedule.Marshal(b, m, deterministic)
}
func (m *Schedule) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Schedule.Merge(m, src)
}
func (m *Schedule) XXX_Size() int {
	return xxx_messageInfo_Schedule.Size(m)
}
func (m *Schedule) XXX_DiscardUnknown() {
	xxx_messageInfo_Schedule.DiscardUnknown(m)
}

var xxx_messageInfo_Schedule proto.InternalMessageInfo

func (m *Schedule) GetID() int32 {
	if m != nil {
		return m.ID
	}
	return 0
}

func (m *Schedule) GetEventsList() []*Event {
	if m != nil {
		return m.EventsList
	}
	return nil
}

type Event struct {
	EventName            string       `protobuf:"bytes,1,opt,name=EventName,proto3" json:"EventName,omitempty"`
	Location             string       `protobuf:"bytes,2,opt,name=Location,proto3" json:"Location,omitempty"`
	EventTime            []*EventTime `protobuf:"bytes,3,rep,name=EventTime,proto3" json:"EventTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Event) Reset()         { *m = Event{} }
func (m *Event) String() string { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()    {}
func (*Event) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{1}
}

func (m *Event) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Event.Unmarshal(m, b)
}
func (m *Event) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Event.Marshal(b, m, deterministic)
}
func (m *Event) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Event.Merge(m, src)
}
func (m *Event) XXX_Size() int {
	return xxx_messageInfo_Event.Size(m)
}
func (m *Event) XXX_DiscardUnknown() {
	xxx_messageInfo_Event.DiscardUnknown(m)
}

var xxx_messageInfo_Event proto.InternalMessageInfo

func (m *Event) GetEventName() string {
	if m != nil {
		return m.EventName
	}
	return ""
}

func (m *Event) GetLocation() string {
	if m != nil {
		return m.Location
	}
	return ""
}

func (m *Event) GetEventTime() []*EventTime {
	if m != nil {
		return m.EventTime
	}
	return nil
}

type EventTime struct {
	DurationInSec           int32                `protobuf:"varint,1,opt,name=DurationInSec,proto3" json:"DurationInSec,omitempty"`
	PrecautionDurationInSec int32                `protobuf:"varint,2,opt,name=PrecautionDurationInSec,proto3" json:"PrecautionDurationInSec,omitempty"`
	ActualStartingTime      *timestamp.Timestamp `protobuf:"bytes,3,opt,name=ActualStartingTime,proto3" json:"ActualStartingTime,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}             `json:"-"`
	XXX_unrecognized        []byte               `json:"-"`
	XXX_sizecache           int32                `json:"-"`
}

func (m *EventTime) Reset()         { *m = EventTime{} }
func (m *EventTime) String() string { return proto.CompactTextString(m) }
func (*EventTime) ProtoMessage()    {}
func (*EventTime) Descriptor() ([]byte, []int) {
	return fileDescriptor_423806180556987f, []int{2}
}

func (m *EventTime) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_EventTime.Unmarshal(m, b)
}
func (m *EventTime) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_EventTime.Marshal(b, m, deterministic)
}
func (m *EventTime) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventTime.Merge(m, src)
}
func (m *EventTime) XXX_Size() int {
	return xxx_messageInfo_EventTime.Size(m)
}
func (m *EventTime) XXX_DiscardUnknown() {
	xxx_messageInfo_EventTime.DiscardUnknown(m)
}

var xxx_messageInfo_EventTime proto.InternalMessageInfo

func (m *EventTime) GetDurationInSec() int32 {
	if m != nil {
		return m.DurationInSec
	}
	return 0
}

func (m *EventTime) GetPrecautionDurationInSec() int32 {
	if m != nil {
		return m.PrecautionDurationInSec
	}
	return 0
}

func (m *EventTime) GetActualStartingTime() *timestamp.Timestamp {
	if m != nil {
		return m.ActualStartingTime
	}
	return nil
}

func init() {
	proto.RegisterType((*Schedule)(nil), "protbuf_adapter.Schedule")
	proto.RegisterType((*Event)(nil), "protbuf_adapter.Event")
	proto.RegisterType((*EventTime)(nil), "protbuf_adapter.EventTime")
}

func init() { proto.RegisterFile("spec.proto", fileDescriptor_423806180556987f) }

var fileDescriptor_423806180556987f = []byte{
	// 275 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x90, 0x41, 0x4b, 0xc3, 0x40,
	0x10, 0x85, 0x49, 0x4a, 0xa5, 0x1d, 0x51, 0x61, 0x0f, 0x1a, 0x82, 0x60, 0x09, 0x1e, 0x7a, 0x4a,
	0x41, 0x41, 0x7a, 0x15, 0xe2, 0x21, 0x52, 0x44, 0x36, 0xbd, 0xcb, 0x66, 0x3b, 0x8d, 0x81, 0x24,
	0x1b, 0x92, 0x59, 0x2f, 0xfe, 0x30, 0xff, 0x9e, 0x64, 0x9a, 0xda, 0x56, 0xda, 0x53, 0x32, 0x33,
	0xdf, 0x9b, 0x37, 0xfb, 0x00, 0xda, 0x1a, 0x75, 0x58, 0x37, 0x86, 0x8c, 0xb8, 0xea, 0x3e, 0xa9,
	0x5d, 0x7f, 0xa8, 0x95, 0xaa, 0x09, 0x1b, 0xff, 0x2e, 0x33, 0x26, 0x2b, 0x70, 0xc6, 0xe3, 0xd4,
	0xae, 0x67, 0x94, 0x97, 0xd8, 0x92, 0x2a, 0xeb, 0x8d, 0x22, 0x90, 0x30, 0x4a, 0xf4, 0x27, 0xae,
	0x6c, 0x81, 0xe2, 0x12, 0xdc, 0x38, 0xf2, 0x9c, 0x89, 0x33, 0x1d, 0x4a, 0x37, 0x8e, 0xc4, 0x13,
	0xc0, 0xcb, 0x17, 0x56, 0xd4, 0x2e, 0xf2, 0x96, 0x3c, 0x77, 0x32, 0x98, 0x9e, 0x3f, 0x5c, 0x87,
	0xff, 0x2c, 0x42, 0x46, 0xe4, 0x1e, 0x19, 0x7c, 0xc3, 0x90, 0x2b, 0x71, 0x0b, 0x63, 0xfe, 0x79,
	0x53, 0x25, 0xf2, 0xde, 0xb1, 0xdc, 0x35, 0x84, 0x0f, 0xa3, 0x85, 0xd1, 0x8a, 0x72, 0x53, 0x79,
	0x2e, 0x0f, 0xff, 0x6a, 0x31, 0xef, 0x95, 0xcb, 0xbc, 0x44, 0x6f, 0xc0, 0xce, 0xfe, 0x71, 0xe7,
	0x8e, 0x90, 0x3b, 0x38, 0xf8, 0x71, 0xf6, 0xa4, 0xe2, 0x1e, 0x2e, 0x22, 0xdb, 0xf0, 0xce, 0xb8,
	0x4a, 0x50, 0xf7, 0xaf, 0x3b, 0x6c, 0x8a, 0x39, 0xdc, 0xbc, 0x37, 0xa8, 0x95, 0xed, 0x5a, 0x87,
	0xbc, 0xcb, 0xfc, 0xa9, 0xb1, 0x78, 0x05, 0xf1, 0xac, 0xc9, 0xaa, 0x22, 0x21, 0xd5, 0x50, 0x5e,
	0x65, 0xfd, 0xc1, 0x0e, 0x1f, 0xbc, 0x09, 0x3f, 0xdc, 0x86, 0x1f, 0x2e, 0xb7, 0xe1, 0xcb, 0x23,
	0xaa, 0xf4, 0x8c, 0xb9, 0xc7, 0xdf, 0x00, 0x00, 0x00, 0xff, 0xff, 0x34, 0xa9, 0x5b, 0x56, 0xd1,
	0x01, 0x00, 0x00,
}
